sudo: required

language: c

jobs:
  fast_finish: true
  include:
  - os: linux
    env: OCAML_VERSION=4.05
  - os: linux
    env: OCAML_VERSION=4.06
  - os: linux
    env: OCAML_VERSION=4.07
  - os: linux
    env: OCAML_VERSION=4.08
  - os: linux
    env: OCAML_VERSION=4.09
  - os: linux
    env: OCAML_VERSION=4.10
  - os: osx
    env: OCAML_VERSION=4.09
  - os: freebsd
    env: OCAML_VERSION=4.09

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then command -v protoc >/dev/null 2>&1 || (brew update && brew install protobuf) ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then command -v protoc >/dev/null 2>&1 || sudo apt-get install -qq protobuf-compiler ; fi
  - if [[ "$TRAVIS_OS_NAME" == "freebsd" ]]; then command -v protoc >/dev/null 2>&1 || sudo pkg install -qy protobuf ; fi

install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh ;
    bash -ex .travis-ocaml.sh ;

script:
  - set -ex ;
    export OPAMYES=1 ;
    export DEPS='benchmark camlp5 cppo dune.1.11.4 jingoo markup num ocaml ounit ocurl piqi piqilib redis redis-sync stdlib-shims unidecode.0.2.0 uucp uutf yojson zarith' ;
    eval $(opam config env) ;
    opam pin list ;
    opam pin remove markup --no-action ;
    opam pin remove piqilib --no-action ;
    opam pin remove piqi --no-action ;
    opam update ;
    opam install depext ;
    opam depext $DEPS ;
    opam install $DEPS ;
    if [[ "$TRAVIS_OS_NAME" == "freebsd" ]]; then gmake ci ; else make ci ; fi ;
    zip geneweb-$TRAVIS_OS_NAME.zip distribution

deploy:
  provider: releases
  api_key:
    secure: WzikH/dQYwS9TogYWIZwaORKY4XYjgtqzNM3+fzlfZa8Hnl7GDcOdk7IdBYFY9Qz548PTvMLQzSCUzgVEX2yaL6a4lS29zsvZluKoDAPWd77641/iKqBmxuwctuKaHTrJmbRfML9zG230Z7OEG1ibYpaskin27oity4e8xCLeAe27cv41BbQ8+P+cD1iYYnEUwrLDeWMh3FtCb2bKWDuRp4pN2b6XrUYFG4Kvo1+cnz2onL7ktnZ6JuhkB+ixUEHL0zUONTP29hh/89XqvLX2fF/31FXc8Nu6sH4PYCuHA8NZ/9iRjB9kLuBlt78XRh1yuv3gKnS0yzgkpz6v/8MEOwDB2NhaRpnQu0yfwEvGaz9Y91JB7JsSQX4rgn8rqFJ16sgY3zl5laa+tha5qhXSsurY2RKf5/WGQsnXgACyMxnksEADLi025d28HqIt3kveVI37ExVDpWa1KHQFKPB+saeHaez/Q4XGNns+VUFldnmDCkW3yB5gIPCPEnXGvq6TgXjO6WqyuM+C6kjx/IMGY/u79w+YnEovHUGl26Pl3mhY0/62JUjmRZ/MLFOa3opMZ2CUC5quWOttyjyUxf5UpR0VldE0uvv4AYqe6zW0rCU8vnrSFM+HHS2ZHHjeBsqpSyYn6GPD78gQ+7yif1MpiGFXaT9l9Jkzu6271bYREE=
  file: "./geneweb-$TRAVIS_OS_NAME.zip"
  on:
    repo: geneweb/geneweb
    branch: binaries-distrib
  skip_cleanup: 'true'
  draft: 'true'
