-
  branches:
    only:
      - binaries-distrib

  skip_commits:
    files:
      - CHANGES
      - ICHANGES
      - etc/
      - geneweb.opam
      - .gitignore
      - hd/
      - INSTALL
      - LICENSE
      - README.md
      - man/
      - .travis.yml

  platform:
    - x64

  environment:
    CYG_BASH: '%CYG_ROOT%/bin/bash -lc'
    OPAM_PACKAGES: 'benchmark camlp5 cppo dune.1.11.4 jingoo markup num ocaml ounit ocurl piqi piqilib redis redis-sync stdlib-shims unidecode.0.2.0 uucp uutf yojson zarith'
    matrix:
      # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      #   CYG_ROOT: C:/cygwin64
      #   PKG_NAME: win64
      #   OPAM_PACKAGES: 'benchmark camlp5 cppo dune.1.11.4 jingoo markup num ocaml ounit stdlib-shims unidecode.0.2.0 uucp uutf zarith'
      # - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
      #   PACKAGE_UPDATE: 'sudo apt-get update'
      #   PACKAGE_INSTALLER: 'sudo apt-get install -qq'
      #   PROTOBUF_COMPILER: 'protobuf-compiler'
      #   PKG_NAME: deb
      - APPVEYOR_BUILD_WORKER_IMAGE: macOS
        PACKAGE_UPDATE: 'brew update'
        PACKAGE_INSTALLER: 'brew install'
        PROTOBUF_COMPILER: 'protobuf'
        PKG_NAME: macos


  install:
    # windows environnement
    - cmd: 'set OPAMYES=1'
    - cmd: 'set PATH=%PATH%;%CYG_ROOT%\usr\x86_64-w64-mingw32\sys-root\mingw\bin'
    - cmd: '%CYG_ROOT%\setup-x86_64.exe -qnNdO -R %CYG_ROOT% -s http://cygwin.mirror.constant.com -l %CYG_ROOT%/var/cache/setup -P rsync -P patch -P diffutils -P unzip -P m4 -P mingw64-x86_64-gcc-core -P mingw64-x86_64-gmp'
    - cmd: '%CYG_BASH% "curl -fsSL -o opam64.tar.xz https://github.com/fdopen/opam-repository-mingw/releases/download/0.0.0.2/opam64.tar.xz"'
    - cmd: '%CYG_BASH% "tar -xf opam64.tar.xz && opam64/install.sh"'
    - cmd: '%CYG_BASH% "opam init -a mingw https://github.com/fdopen/opam-repository-mingw.git#opam2 -c 4.09.0+mingw64c --disable-sandboxing"'
    - cmd: '%CYG_BASH% "opam install ${OPAM_PACKAGES}"'
    - cmd: '%CYG_BASH% "eval $(ocaml-env cygwin)"'
    # unix environnement
    - sh: 'set OPAMYES=1'
    - sh: 'sudo chown -R appveyor:staff $HOME/.cache' # for macos only : permissions issue
    - sh: 'ls -al $HOME/.cache'
    - sh: 'if [[ "$APPVEYOR_BUILD_WORKER_IMAGE" == "Ubuntu1604" ]]; then sudo add-apt-repository ppa:avsm/ppa; fi;'
    - sh: '$PACKAGE_UPDATE'
    - sh: '$PACKAGE_INSTALLER opam $PROTOBUF_COMPILER'
    - sh: 'export DEPS="benchmark camlp5 cppo dune.1.11.4 jingoo markup num ocaml ounit ocurl piqi piqilib redis redis-sync stdlib-shims unidecode.0.2.0 uucp uutf yojson zarith"'
    - sh: 'opam init'
    - sh: 'eval $(opam config env)'
    - sh: 'opam pin list'
    - sh: 'opam pin remove markup --no-action'
    - sh: 'opam pin remove piqilib --no-action'
    - sh: 'opam pin remove piqi --no-action'
    - sh: 'opam update -y'
    - sh: 'opam install -y depext'
    - sh: 'opam depext -y $OPAM_PACKAGES'
    - sh: 'opam install -y $OPAM_PACKAGES'

  test_script:
    - cmd: '%CYG_BASH% "cd ${APPVEYOR_BUILD_FOLDER} && BENCH_FILE=geneweb-bench.tmp.bin make ci"'
    - sh: 'if [[ "$TRAVIS_OS_NAME" == "freebsd" ]]; then gmake ci ; else make ci ; fi'

  build_script:
    - sh : 'ocaml ./configure.ml --sosa-legacy && make clean distrib'
    - sh : 'zip -r geneweb-$PKG_NAME.zip distribution/*'
    - cmd: '%CYG_BASH% "cd ${APPVEYOR_BUILD_FOLDER} && ocaml ./configure.ml --sosa-legacy && make clean distrib"'
    - cmd: 7z a geneweb-%PKG_NAME%.zip %APPVEYOR_BUILD_FOLDER%\distribution

  artifacts:
    - path: geneweb-%PKG_NAME%.zip
      name: GeneWeb with default options
    - path: geneweb-zarith.zip
      name: GeneWeb with --sosa-zarith option

  deploy:
    release: myproduct-v$(appveyor_build_version)
    description: 'Release description'
    provider: GitHub
    auth_token:
      secure: SeKOGhnICJvaDizFLOLbds/4bYK3WSZJmL6jVVL4a52zefGDIyqhVc07OxvXMaz9
    artifact: geneweb-%PKG_NAME%.zip
    draft: false
    prerelease: false
